# Site settings
title: The chinternet with Alex Chin.
email: alex@alexchin.co.uk
description: > # 
  aLeXCHin's home on the web.

# the subpath of your site, e.g. /blog/
baseurl: "" 

# the base hostname & protocol for your site
url: "http://www.alexchin.co.uk"
linkedin_username: alexpchin
twitter_username: alexpchin
github_username:  alexpchin

# Build settings
markdown: kramdown

exclude: [".sass-cache", "_site", "vendor"]