# Directory Settings
source: ./src
destination: ./build
plugins: ./src/_plugins

# Site Specific Settings
timezone: United_Kingdom/London
permalink: /:title
url: http://www.alexchin.co.uk
default_page_image: http://www.alexchin.co.uk/images/alex.png
default_home_image: http://www.alexchin.co.uk/images/alex.png
title: Alex Chin's little space on the web.
description: "Coffee & code. Start-up tips and coding tricks by Alex Chin."
future: false
send_to_buffer: true
buffer_profiles:
    - 53df98d2a3f420da7f65c445

# Syndication Settings
# feed: http://feeds.feedburner.com/neverstopbuilding/TGMp

#Builder Information
author: Alex Chin
email: alex@alexchin.co.uk
twitter: //twitter.com/alexpchin
twitter_username: alexpchin
github: //github.com/alexpchin
instagram: //instagram.com/alexpchin
from: "Shoreditch, London, United Kingdom"
author_facebook: https://www.facebook.com/alexpchin
google_plus: //plus.google.com/102653289559667402852
# youtube: //www.youtube.com/user/alexpchin

# Plugin Settings
markdown: redcarpet
highlighter: true

asset_pipeline:
  bundle: true
  compress: true
  output_path: assets
  display_path: nil
  gzip: true

sitemap:
  # local: false
  file: "/sitemap.xml"
  exclude:
      - "/atom.xml"
      - "/feed.xml"
      - "/feed/index.xml"
  include_posts:
      - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"

# category_dir: category