# Site settings
title: aLeXCHiN
email: alex@alexchin.co.uk
description: > # 
  aLeXCHin's home on the web.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.alexchin.co.uk" # the base hostname & protocol for your site
twitter_username: alexpchin
github_username:  alexpchin

# Build settings
markdown: kramdown
