source: ./src
plugins: ./src/_plugins

# Site settings
timezone: United_Kingdom/London
permalink: /:title
url: http://www.alexchin.co.uk
default_page_image: http://www.alexchin.co.uk/images/alex.png
default_home_image: http://www.alexchin.co.uk/images/alex.png
description: "Coffee & code. Start-up tips and coding tricks by Alex Chin."
title: The chinternet with Alex Chin.
email: alex@alexchin.co.uk
description: > # 
  Welcome to the Chinternet.lol

# the subpath of your site, e.g. /blog/
baseurl: "" 

# the base hostname & protocol for your site
url: "http://www.alexchin.co.uk"
linkedin_username: alexpchin
twitter_username: alexpchin
github_username:  alexpchin

# Build settings
markdown: kramdown